---
output:
  pdf_document: default
  html_document: default
widgets:
- mathjax
- bootstrap
- quiz
- shiny
- interactive
- latex_macros
---

# STAT 456  Final Project
# Spring 2024


&nbsp;

#### Instructions: 

* Please take a quick read through these project instructions now, and then review them more carefully later to fully understand what is required to manage this project. If you have any general questions or need clarification on the problems described below, please email me by May 1.

* You are allowed to use your textbook as well as other reference books you feel you might need. You should conduct your analysis using the statistical software R/Rstudio and write your report using Rmarkdown. 

* Each group will deliver a presentation of the project in class on May 2, from 4:30 PM to 7:00 PM. Please refer to the detailed instructions and evaluation criteria provided below for guidance.

* Please do not ask your professor or TA to debug your codes. You are strictly prohibited from seeking assistance from anyone other than your professor. The use of generative AI tools is not permitted for this group project. Adherence to George Mason University's academic integrity policy is expected. Any unauthorized assistance will result in project failure.

* Submit the following three files to Blackboard: a PDF of your report, the .Rmd file, as well as your presentation slides.

**Good luck!**


\newpage


## Problem Statement

A Chinese automobile company, Geely Auto, aims to enter the US market by establishing a local manufacturing unit to produce cars and compete with US and European counterparts. They have contracted an automobile consulting company to analyze the factors influencing car pricing in the American market, which may differ significantly from the Chinese market. The company seeks to understand:

* Which variables significantly predict the price of a car?

* How well these variables explain car prices?

Based on extensive market surveys, the consulting firm has collected a large dataset of various car types across the American market.


**Business Goal**

The task is to model car prices using available independent variables. The model will assist management in understanding how prices vary with independent variables, enabling them to adjust car design, business strategy, etc., to meet specific price levels. In additon, the model will provide insights into pricing dynamics in a new market. 


**Data**

The dataset is provided in `CarPrice_Assignment.csv`. The data dictionary is `Dictionary-carprices.xlsx`

There are $205$ observations. To judge the predictive performance of your selected model, please hold the last $40$ observations as the test set to estimate the prediction error $\sum_{i=166}^{205}(Y_i-\hat{Y}_i)^2$. So only use the first 165 observations for estimating/training your model.

**Methods**

You might want to conduct some preliminary data exploration first using data visualization and statistical techniques to describe dataset characterizations, such as size, quantity, and relationship, in order to better understand the nature of the data. Also, you may need to run the following steps multiple times to finally reach the **business goal** stated above. 

*Step 1.* Identify the model variables for statistical analysis. Consider techniques such as pairwise scatterplot analysis, predictor transformations, stepwise selection using criteria like AIC, BIC, k-fold cross-validation (CV), and LASSO.

*Step 2.* Evaluate the identified model for association and prediction analysis. Utilize diagnostic tools to assess model assumptions, address outliers if there are any, and consider interactions among predictors.

*Step 3.* Conduct statistical inference to claim significant associations and develop a prediction model. Utilize the test set to calculate prediction error and validate model performance.

## Part 1. Written Report

Prepare a written report documenting your analysis and findings for the Geely Auto project. Your report should be clear, concise, and organized, providing a comprehensive overview of your methodology, results, and conclusions. 

Every report should have the title (STAT 456 ~ Final Project), authors, and date on the first page. All tables and figures should be clearly labeled and numbered.  For your pdf, all pages should be numbered, and set the font size of the main body of the report to be 12pt. Make sure you proofread your report before submitting it.

The use of generative AI tools is not permitted for writing this report.

### Evaluation Criteria:

**Clarity and Organization (10 points):** 

* Clear and well-organized presentation of analysis methods and findings.
* Logical flow of information from data exploration to model evaluation.

**Depth of Analysis (20 points):** 

* Comprehensive exploration of the dataset, including summary statistics and visualization.
* Rigorous application of modeling techniques and diagnostics.

**Methodological Rigor (40 points):** 

* Appropriate selection and implementation of statistical methods for modeling.
* Correct application of model diagnostics to assess assumptions and model fit.
* Calculation and comparison of prediction error metrics (e.g., RMSE) using test set data.
* Emphasis on achieving smaller prediction errors to demonstrate model effectiveness.

**Interpretation and Insight (10 points):** 

* Effective interpretation of model results and significance tests.
* Insightful discussion of the implications of findings for Geely Auto.

**Presentation and Visuals (10 points):** 

* Clear and informative visualizations that enhance understanding of the data and analysis.
* Professional formatting and labeling of figures and tables.

**Conclusions and Recommendations (10 points):** 

* Well-supported conclusions based on the analysis and interpretation of results.
* Actionable recommendations provided for Geely Auto based on the analysis.

## Part 2. Presentation

Each student group will deliver a presentation on their analysis and findings from the project on May 2, 2024. The presentation should be structured to effectively communicate key aspects of the project and showcase the group's understanding of the data and analysis techniques used. Below are the recommended components for the presentation: introduction and data exploration; model building; model evaluation; conclusion and recommendations.

The presentation should look as if only one person created it. So agree upon format before dividing up making slides. 


### Evaluation Criteria:

**Content (40 points):**

* Clarity and completeness of project introduction.
* Thoroughness and effectiveness of data exploration.
* Soundness of model-building approach and variable selection.
* Comprehensive evaluation of model performance.
* Appropriateness and relevance of conclusions and recommendations.

**Delivery (30 points):**

* Organization and structure of the presentation.
* Clarity and coherence of verbal explanations.
* Engagement and interaction with the audience.
* Time management and adherence to allocated time slots.
* Clarity and accuracy of responses to audience questions if there are any.

**Visual Aids (20 points):**

* Quality and relevance of visualizations.
* Use of visual aids to enhance understanding and support key points.



